wip, started calib app

diff --git a/autocrop b/autocrop
--- a/autocrop
+++ b/autocrop
@@ -15,7 +15,13 @@ mkdir -p $2
 
 for fn in $1/*
 do
-	echo "processing file $fn"
+	echo "- processing file $fn"
 	trombino_autocrop.py $fn $2
+	errval=$?
+	if ! [ $errval = 0 ]
+	then
+		echo "Failure, cropping app returned $errval, stopping"
+		exit 1
+	fi
 done
 
