wip

diff --git a/autocrop b/autocrop
--- a/autocrop
+++ b/autocrop
@@ -7,8 +7,8 @@ set +x
 
 
 if [ "$#" -lt 2 ]; then
-    echo "2 arguments requested"
-    exit 1
+	echo "-autocrop: 2 arguments requested"
+	exit 1
 fi
 
 # etape 1: lecture des parametres
@@ -16,11 +16,14 @@ fi
 src_dir=$1
 dst_dir=$2
 
-modemanual=0
 if [ "$1" = "-m" ]
 then
-	modemanual=1
+	modemanual=$1
 	src_dir=$2
+	if [ "$#" -lt 3 ]; then
+		echo "-autocrop: missing destination folder, exiting..."
+		exit 1
+	fi
 	dst_dir=$3
 fi
 
@@ -29,12 +32,12 @@ mkdir -p "$dst_dir"
 
 for fn in $src_dir/*
 do
-	echo "- processing file $fn"
+	echo "-autocrop: processing file $fn"
 	trombino_autocrop_gui.py "$fn" "$dst_dir" $modemanual
 	errval=$?
 	if ! [ $errval = 0 ]
 	then
-		echo "Failure, cropping app returned $errval, stopping"
+		echo "-autocrop: failure, cropping app returned $errval, stopping"
 		exit 1
 	fi
 done
